spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/autobahn
    username: 
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL 8 and later
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
